### ISSUE TITLE
Add support for serialization

### ISSUE THREAD

**Issue by bnaras** [JamesYang007/adelie#138]
It would be very useful to pickle an adelie model and load it later for predictions, which is not possible currently. I can manage temporarily by writing serialize and deserialize methods that work for myself by picking off the sparse matrices etc. but to make this approach general, I can't seem to find a factory method to deserialized an arbitrary adelie model.

**Comment by JamesYang007** [comment]
Yes thanks for making the issue for this! I myself have been wanting this feature for some time, but I got around it by just writing my own simple serializer. Doing this carefully I think requires some thought though. I'll spend some time after the defense. I just have to think through what should be serialized and not.

**Comment by cyradil** [comment]
I wanted to add a note here that adelie does not like the deep copy function (copy.deepcopy()). Based on the error I got I believe it is due to the not being able to pickle. When this feature is added have a test for the copy function would be appreciated!

**Comment by JamesYang007** [comment]
Yes pickling will definitely solve both of these issues :).

**Comment by jwijffels** [comment]
I'm also looking for this. Currently I get these types of errors. 
@bnaras / @JamesYang007 Is there a solution for this to save the model?

```
>>> def savePickle(data: object, file: str, version: int = 4) -> str:
>>>     with open(file, "wb") as f:
>>>         pickle.dump(data, f, protocol=version)
>>>     return f.name
>>> type(model._state)
<class 'adelie.state.glm_naive.<locals>._glm_naive'>
>>> savePickle(model._state, "adelie.pickle")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in savePickle
TypeError: cannot pickle '_glm_naive' object
```
